# helm/calico/values.production.yaml
installation:
  calicoNetwork:
    ipPools:
      - blockSize: 24
        cidr: 10.244.0.0/14
        encapsulation: VXLAN
        natOutgoing: Enabled
        nodeSelector: all()
  nodeMetricsPort: 9091
  typhaMetricsPort: 9093
  typhaAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
