# helm/kube-prometheus-stack/values.production.yaml
prometheus:
  prometheusSpec:
    replicas: 2
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 200Gi

alertmanager:
  alertmanagerSpec:
    replicas: 3

grafana:
  replicas: 2
  persistence:
    size: 20Gi
