# helm/keda/values.yaml
# KEDA base values

replicaCount: 1

operator:
  name: keda-operator
  replicaCount: 1

metricsServer:
  replicaCount: 1
  useHostNetwork: false

webhooks:
  enabled: true
  replicaCount: 1

prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
  operator:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring

resources:
  operator:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  metricServer:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

podDisruptionBudget:
  operator:
    minAvailable: 1
  metricServer:
    minAvailable: 1
