# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/api.proto\x12\x04lens\"F\n\nVideoFrame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\x14\n\x0c\x66rame_number\x18\x02 \x01(\x05\x12\x0e\n\x06pts_ms\x18\x03 \x01(\x03\"M\n\nFrameScore\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x15\n\ranomaly_flags\x18\x03 \x03(\t2F\n\x0c\x41nalyzeMedia\x12\x36\n\x0cStreamFrames\x12\x10.lens.VideoFrame\x1a\x10.lens.FrameScore(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOFRAME']._serialized_start=25
  _globals['_VIDEOFRAME']._serialized_end=95
  _globals['_FRAMESCORE']._serialized_start=97
  _globals['_FRAMESCORE']._serialized_end=174
  _globals['_ANALYZEMEDIA']._serialized_start=176
  _globals['_ANALYZEMEDIA']._serialized_end=246
# @@protoc_insertion_point(module_scope)
